version: '3'
services:
  nginx:
    build: ./docker/nginx
    working_dir: /var/www
    volumes:
      - ./:/var/www
  php:
    build: ./docker/php
    working_dir: /var/www
    volumes:
      - ./:/var/www
  mysql:
    build: ./docker/mysql
